In [ ]:
# would be nice to try computing ResNet mebedding similarities

In [1]:
import tensorflow as tf

In [9]:
# instantiate resnet model
# model = tf.keras.applications.resnet50.ResNet50(
#     include_top=False, weights='imagenet', #input_tensor=None, input_shape=None,
#     pooling=max
# )


In [ ]:
# preprocess sample input
# x = 
# tf.keras.applications.resnet50.preprocess_input(
#     x, data_format=None
# )
# # query for generated image: person on a skateboard walking his dog
# an original caption: a man riding a skateboard with his dog

In [12]:
# adapt
# i = tf.keras.layers.Input([512, 512, 3], dtype = tf.uint8)
# x = tf.cast(i, tf.float32)
# x = tf.keras.applications.resnet50.preprocess_input(x)
# # core = tf.keras.applications.resnet50.ResNet50()
# x = model(x)
# net = tf.keras.Model(inputs=[x], outputs=[])

# image = tf.image.decode_jpeg(tf.io.read_file('cog-view-apple.jpg'))

# result = net(image)

ValueError: Found unvisited input tensors that are disconnected from the outputs: [<KerasTensor: shape=(None, 16, 16, 2048) dtype=float32 (created by layer 'resnet50')>]

In [28]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet', include_top=False, pooling=max)

img_path = 'cog-view-apple.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features_apple = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Features shape:', features_apple.shape)
features_apple_flat = tf.reshape(features_apple, -1)
features_apple_flat.shape

Features shape: (1, 7, 7, 2048)


TensorShape([100352])

In [26]:
img2_path = 'cog-view-sample2.jpg'
img2 = image.load_img(img2_path, target_size=(224, 224))
x2 = image.img_to_array(img2)
x2 = np.expand_dims(x2, axis=0)
x2 = preprocess_input(x2)

features_cog_skateboard = model.predict(x2)
features_cog_skateboard.shape
features_cog_skateboard_flat = tf.reshape(features_cog_skateboard, -1)
features_cog_skateboard_flat.shape

TensorShape([100352])

In [25]:
img3_path = 'person-skateboard-dog-coco.png'
img3 = image.load_img(img3_path, target_size=(224, 224))
x3 = image.img_to_array(img3)
x3 = np.expand_dims(x3, axis=0)
x3 = preprocess_input(x3)

features_coco_skateboard = model.predict(x3)
features_coco_skateboard.shape
features_coco_skateboard_flat = tf.reshape(features_coco_skateboard, -1)
features_coco_skateboard_flat.shape

TensorShape([100352])

In [31]:
tf.tensordot(features_coco_skateboard_flat, features_cog_skateboard_flat, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=31308.82>

In [29]:
tf.tensordot(features_coco_skateboard_flat, features_apple_flat, 1)
# 19613 if axis 1

<tf.Tensor: shape=(), dtype=float32, numpy=19613.654>

In [32]:
tf.tensordot(features_cog_skateboard_flat, features_apple_flat, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=20554.45>